### PR TITLE
 Upgrade transformers version

### PR DESCRIPTION
**Pull request by HDThang**
Upgrade transformers to version 4.36

### CODE REVIEW

**Comment by yeomni** [comment]
Well I don't think we can possibly review all those thousands of changes. We'd rather focus on looking at some major changes that might have a significant impact on our framework.

**Comment by HDThang** [comment]
Most of the files are .md and yml, the files should be requires is the ones inside `examples/pytorch`

**Comment by yeomni** [comment]
I've only reviewed python scripts under `examples/pytorch` and they looked OK to me.

**Review by loctxmoreh — APPROVED** [review]
LGTM

**Comment by loctxmoreh** [comment]
I reviewed the scripts under `examples/pytorch` and found no issue. Changes are mostly on authentication to HuggingFace Hub. 

One can use this cmd: `git diff main upgrade_transformers_version -- examples/pytorch/**/*.py` to look at the diff, instead of opening up in the browser. My browser tab freezes under this massive diff :face_exhaling:

**Pull request merged**
